# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Orbitale.tech
#email: alex@orbitale.tech
description: >
    It's just me trying to find useful things to do for the world of programming, expecially for the web.
baseurl: ""
url: "http://www.orbitale.tech"
twitter_username: pierstoval
github_username:  pierstoval

author: Alex Rock

# Build settings
markdown: kramdown
theme: minima
plugins:
    - jekyll-feed

google_analytics: UA-43812649-3

feed:
    path: feed.xml

defaults:
    - scope:
          path: 'img/'
      values:
          images: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#     - Gemfile
#     - Gemfile.lock
#     - node_modules
#     - vendor/bundle/
#     - vendor/cache/
#     - vendor/gems/
#     - vendor/ruby/
